on:
  push:
    branches:
      - production
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.9
        with:
          release-type: node
          package-name: pressbooks-build-tools
          include-v-in-tag: false
